name: Auto publish to public site

on:
  push:
    branches:
      - master  # 这里的意思是当 main分支发生push的时候，运行下面的jobs，这里先改为github-actions

jobs:
  hugo-publish: # 任务名自取
    name: publish content to public site
    runs-on: centos-7.9	# 在什么环境运行任务
    steps:
      - name: Setup Hugo	# 步骤名自取
        uses: peaceiris/actions-hugo@v2	# hugo官方提供的action，用于在任务环境中获取hugo
        with:
          hugo-version: '0.105.0'	# 获取最新版本的hugo
          extended: true

      - name: Build
        working-directory: ./
        run: hugo --minify --gc --cleanDestinationDir